### ISSUE TITLE
Update on Static and dynamic mix?

### ISSUE THREAD

**Issue by codica-studio** [dcasia/nova-dashboard#11]
_Note: While possible to mix Static and Dynamic Widgets the static ones gets shifted around due to the lack of a setting to lock an item on the grid, this will likely be fixed once the original author of the underlying grid library accepts the suggestion of developing such feature: https://github.com/bensladden/vue-responsive-dash/issues/196_

This was completed Aug..6th I believe. Just curious if you have had a chance to test / implement. Thanks!

**Comment by milewski** [comment]
Unfortunately, I still haven't got the time to get back into the development of this package...

**Comment by codica-studio** [comment]
Well, thank you for the work on this. I will try to help out in the next few weeks. I'd like to see this develop. It's quite useful.
