### ISSUE TITLE
Replacing default dashboard

### ISSUE THREAD

**Issue by xoco70** [dcasia/nova-dashboard#13]
Did you find a trick to replace default dashboard with this one using digital-creative/collapsible-resource-manager?

**Comment by milewski** [comment]
Nova does not provide any option for replacing the default dashboard,... My tricky currently is create a dummy card and using it on the main dashboard.. The purpose of this card is simply redirect to another page.. So as soon as the page loads.. It's shows a loading loader and redirects to my actual dashboard
