### ISSUE TITLE
Hiding dashboards from sidemenu when having only 1 item

### ISSUE THREAD

**Issue by xoco70** [dcasia/nova-dashboard#16]
Hi,

I have only 1 dashboard, I would like to hide the whole dashboard items ( Dashboards and subitem my-dashboard ).

Is it currently possible to hide the whole dashboard without losing dashboard ( if I remove it from NovaServiceProvider, it also disappear )

**Comment by milewski** [comment]
Yeah do like:

```
 NovaDashboard::make([...])->withoutNavigationMenu()|
```

**Comment by milewski** [comment]
And also an undocumented featured, but if you are using the CollapsibleResourceManager you can link direcly to a dashboard by calling:

```php
WidgetResource::make(MainDashboard::class)->label('Reports')->canSee(fn() => true/false)),
```

**Comment by xoco70** [comment]
added a PR to include it, I will also add doc to CollapsibleResourceManager this afternoon!
