### ISSUE TITLE
syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by shahabzebare** [dcasia/nova-dashboard#2]
::Composer\Autoload\includeFile
vendor/digital-creative/nova-dashboard/src/NovaDashboard.php:13

**Comment by milewski** [comment]
I think this is due to the version of php you are using, what version is it?

**Comment by haxifang-aircos** [comment]
I have the same problem. My VERSION of PHP is 7.4.6

**Comment by milewski** [comment]
Guys the line in the error is this one https://github.com/dcasia/nova-dashboard/blob/master/src/NovaDashboard.php#L13 are you sure you are using php 7.4? It should support property type hint

**Comment by haxifang-aircos** [comment]
I am sure the version is  7.4.6. What version do you have?

**Comment by milewski** [comment]
Im currently on: PHP 7.4.8 (cli) (built: Jul  9 2020 23:47:36) ( NTS )

However it should work since PHP 7.4, are you sure that your host machine is using 7.4 but your web server is actually using an older version?

**Comment by cord** [comment]
works here with php 7.4.5
