### ISSUE TITLE
Multiple Dashboard link doesn't work 

### ISSUE THREAD

**Issue by reksmeysrey** [dcasia/nova-dashboard#21]
in NovaServiceProvider.php
![image](https://user-images.githubusercontent.com/35394133/96605220-1f4db680-1320-11eb-9391-ae6026f73f10.png)

in Sidebar.
![image](https://user-images.githubusercontent.com/35394133/96605269-31c7f000-1320-11eb-94ea-bc4d34ef0278.png)

It shows on sidebar as different url but It's not work as url.
It's doesn't work with multiple dashboard when I'm click on it?
# HELP

**Comment by cord** [comment]
This is a nova issuer - I hope this to be solved soon, see https://github.com/laravel/nova/pull/1083

**Comment by crynobone** [comment]
laravel/nova#1083 only affect `Update.vue` resource. Not related to Dashboard navigation.

**Comment by cord** [comment]
@crynobone thanks for checking this issue.

The nova-dashboard package is not related to the default dashboard in nova, but is a tool, which loads custom pages.

These URLs of these pages look like `/nova/nova-dashboard/(id-of-dashboard)`.

When switching directly between the URLs (e.g. by custom build direct links in the nova navigation) like the following:

`/nova/nova-dashboard/3 `

`/nova/nova-dashboard/7`

only the first clicked page is loaded, when clicking on another link the URL in the browser is updated, but the page is not refreshed. With doing a browser reload the page is refreshed and displayed correctly.


So in my understanding laravel/nova#1083 is similar to this issue? but now I see it would only affect URLs like 
`/resources/users/2/edit` ? 

Wonder if you could apply the same fix to this situation? It would allow us to use direct links to any resource in Nova.

**Comment by crynobone** [comment]
It seem that `Dashboard.vue` need to have it's own `beforeRouteUpdate()` method which need to run `fetchDashboard()`.

You may create a PR on that on `laravel/nova`, Or create an issue to `laravel/nova-issues` and I'll look into it.

**Comment by cord** [comment]
@crynobone thanks, see https://github.com/laravel/nova-issues/issues/3085

**Comment by crynobone** [comment]
https://github.com/dcasia/nova-dashboard/blob/42dc445ddfa30d71987e8db058f2a406b3f8a4ac/resources/js/tool.js#L6-L12

It seem this package define it's own `Dashboard.vue`, so that Vue component need to have it's own `beforeRouteUpdate()` method. This should be done in this package and not `laravel/nova`.

**Comment by milewski** [comment]
Fixed on the latest version. now switching between dashboard re-render the Dashboard.vue component
