### ISSUE TITLE
New filter released

### ISSUE THREAD

**Issue by xoco70** [dcasia/nova-dashboard#23]
Hi, 

I've just released a date filter. It is a mix between pill filter and dateRangeFilter :)

Check it out. This filter is meant to limit date range that user would need when querying a dashboard with charts.

It can only be used with dcasia/nova-dashboard.

https://github.com/sunchain-fr/nova-dates-pill-filter

**Comment by milewski** [comment]
Hi latest version now supports any filter, as long it works in nova4 should work with this package as well
