### ISSUE TITLE
static mode is not working for widget

### ISSUE THREAD

**Issue by xoco70** [dcasia/nova-dashboard#25]
Hi, 

When adding a widget in static mode, with 5 params, it says it wants 0 or 4 : 

```
if ($argumentsCount !== 0 && $argumentsCount !== 4) {

            throw new RuntimeException('Invalid number of arguments, expected: { int $x, int $y, int $width, int $height } or none.');

        }
```

so static mode is not working. 

How to pass options to a widget ???

**Comment by cord** [comment]
`->withMeta($options)`

**Comment by xoco70** [comment]
Ah, thanks for the tip, @cord 

I couldn't make it :( 

Here is how I am doing it : 

```
public function widgets(): array
    {
        $widget = new ConsumedSolarEnergyValue(0, 0, 2, 1);
        $options = [
            "prefix" => null,
            "suffix" => "kWh",
            "decimal" => "2",
            "no_current_data" => "N\/A",
            "labels" => [
                "No Prior Data" => "Aucune donn\u00e9e plus ancienne",
                "No Current Data" => "Aucune donn\u00e9e",
                "No Increase" => "Pas d\u2019augmentation",
                "Increase" => "Augmentation",
                "Decrease" => "Diminution",
                "Previous Value" => "Previous value:"
            ],
            "widget_title" => "Energie r\u00e9seau consomm\u00e9e",
            "widget_help" => null
        ];
        $widget->withMeta(['options' => $options]);
        return [
            $widget,
        ];
    }
```

If I change it to 

`        $widget->withMeta(['optionsXXX' => $options]);`,

 I can see the `optionsXXX` value when checking `/nova-vendor/nova-dashboard/tableau-de-bord`.

but when I use `options`, it seems to be overwritting the $options variable with null values.

**Comment by cord** [comment]
check 

https://github.com/Nova-BI/nova-dashboard-manager/blob/main/src/Views/CustomView.php 

https://github.com/Nova-BI/nova-dashboard-manager/blob/main/src/Models/Datavisualables/BaseDatavisualable.php

for an example how to work with meta data.

**Comment by xoco70** [comment]
mmm. Still can't find it. I think withMeta may not be the problem, it is just overwritten by empty defaults, and I can't find to see why.
