### ISSUE TITLE
Problem with nova version

### ISSUE THREAD

**Issue by ArtMin96** [dcasia/nova-dashboard#3]
The package seems too great. But I have a problem with the nova version. I have nova 2.11.0 and composer say:

optimistdigital/nova-translatable 1.5.0 requires laravel/nova ^2.9 || ^3.0 -> satisfiable by laravel/nova[2.x-dev].

Which version do I need to use your package?

**Comment by milewski** [comment]
It doesn't seems like an issue with this package, looks like you have a version of optimistdigital/nova-translatable that is not supported on your nova version,

This package has no dependencies, and i have not tested it on nova 2 I don't know if it can work with that... The version I use currently is nova 3.8.2
