### ISSUE TITLE
Charts are not updated when changing filters

### ISSUE THREAD

**Issue by xoco70** [dcasia/nova-dashboard#32]
Hi, 

After updating the the latest version  ( 2b82fea6b9403eaf1d5705e66310804e81550121 )
While all my value filters are working well, my chart now has a problem. If I change a filter, chart will not update. I checked that all queries are being well executed ( the changing params are OK). 

The latest commit that is working for me is : 

9032a6be4bcff7b7f86cd588fd1e2f1c3d340c96

After that, chart is not taking the filters modification.

**Comment by marispro** [comment]
Hi,
do you have any errors in dev console log output?

**Comment by xoco70** [comment]
Nop, nothing on the console. Also checked in the debugbar, and all queries are OK. Everything looks just fine, my 3 Value Widgets are updating well. This is only a problem with ChartJS widget. when selecting new value in filter, chart is "blinking", which might indicate chart is refreshing itself, but it doesn't take new values

**Comment by WelaurS** [comment]
Not nova-dashboard related issue, fixed in https://github.com/dcasia/chartjs-widget/pull/10
