### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by xoco70** [dcasia/nova-dashboard#4]
You forgot this line in README. Quite important !

**Comment by xoco70** [comment]
Your component is amazing ! I would like to include a widget that is based on ChartJS component, but I don't exactly know how to do it. I'm not bad in Laravel, but not good at VueJS. I would love to make a PR, but I don't know if I have the skills... Let me try !

**Comment by milewski** [comment]
Ooops! yeah I forgot the migration!... thanks for the reminder I will update it..

Im working on a chart widget right now actually...

![image](https://user-images.githubusercontent.com/2874967/88817103-b27ac280-d1ef-11ea-9b48-6b444a83ff17.png)

 it is super easy to make widgets.. You can copy and paste this one as a starting point: https://github.com/dcasia/value-widget

**Comment by marctich** [comment]
> Ooops! yeah I forgot the migration!... thanks for the reminder I will update it..
> 
> Im working on a chart widget right now actually...
> 
> ![image](https://user-images.githubusercontent.com/2874967/88817103-b27ac280-d1ef-11ea-9b48-6b444a83ff17.png)
> 
> it is super easy to make widgets.. You can copy and paste this one as a starting point: https://github.com/dcasia/value-widget

Would be awesome to see a working chart widget as sample!

**Comment by milewski** [comment]
https://github.com/dcasia/chartjs-widget this is still a work in progress...

**Comment by milewski** [comment]
I think Im done! ... created a barchart and a line chart.. pie/radial will make later... now the only thing left is to write the docs... which is the hardest part of this job....

![image](https://user-images.githubusercontent.com/2874967/88948489-91d06c80-d2c4-11ea-9011-c7549180d06f.png)
![image](https://user-images.githubusercontent.com/2874967/88948577-ad3b7780-d2c4-11ea-9b35-d027488545f3.png)

**Comment by xoco70** [comment]
I will give it a try tomorrow !

**Comment by xoco70** [comment]
this is not so simple without proper docs :/

**Comment by xoco70** [comment]
I tried it once more. I could implement a custom value card. Now, with chartJS, I get: 


```
TypeError: Cannot read property 'display' of null
    at a.mounted (chartjs-widget:formatted:22269)
    at It (vendor.js?id=911c9c048b8f4c9bbb3b:1)
    at en (vendor.js?id=911c9c048b8f4c9bbb3b:1)
    at Object.insert (vendor.js?id=911c9c048b8f4c9bbb3b:1)
    at x (vendor.js?id=911c9c048b8f4c9bbb3b:1)
    at a.__patch__ (vendor.js?id=911c9c048b8f4c9bbb3b:1)
    at a.t._update (vendor.js?id=911c9c048b8f4c9bbb3b:1)
    at a.hn.before (vendor.js?id=911c9c048b8f4c9bbb3b:1)
    at hn.get (vendor.js?id=911c9c048b8f4c9bbb3b:1)
    at hn.run (vendor.js?id=911c9c048b8f4c9bbb3b:1)
```

This make a reference to :

```
scales: {
                    xAxes: [{
                        display: this.options.horizontalAxis.display,

```

What I did:
added this line to `composer.json`

    ```    "digital-creative/chartjs-widget": "dev-master",```

Copy paste the new Widget, and added it in my view with :

``` new SampleLineChart(0, 0, 2, 1, [])```

Is there some mandatory properties ?

**Comment by Pamposgsk** [comment]
> I think Im done! ... created a barchart and a line chart.. pie/radial will make later... now the only thing left is to write the docs... which is the hardest part of this job....
> 
> Any feedback is welcome.. I have added a basic readme with a simple example of how to use: https://github.com/dcasia/chartjs-widget
> 
> ![image](https://user-images.githubusercontent.com/2874967/88948489-91d06c80-d2c4-11ea-9011-c7549180d06f.png)
> ![image](https://user-images.githubusercontent.com/2874967/88948577-ad3b7780-d2c4-11ea-9b35-d027488545f3.png)



Hi ,
Iam getting the following error.Can you please help?


Could not check compatibility between App\Nova\Dashboards\Widgets\SampleLineChart::resolveValue(Illuminate\Support\Collection $options, DigitalCreative\NovaDashboard\Filters $filters): DigitalCreative\ChartJsWidget\ValueResult and DigitalCreative\NovaDashboard\Widget::resolveValue(Illuminate\Support\Collection $options, DigitalCreative\NovaDashboard\Filters $filters): DigitalCreative\NovaDashboard\ValueResult, because class DigitalCreative\ChartJsWidget\ValueResult is not available
