### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by milewski** [dcasia/nova-dashboard#5]
Docs were quickly written, there are grammar mistakes.. and many things are missing such as 

- [ ] migration, 
- [ ] how to create widgets, 
- [ ] how to publish config to customize database model and tables, 
- [ ] better examples, 
- [ ] how to use the widgets as standard nova cards
- [ ] how to use the WidgetResource::class to direcly link to a view using collapsible-resource-mananger
- [ ] write docs for the value-widget and the chartjs-widget

**Comment by marctich** [comment]
> Docs were quickly written, there are grammar mistakes.. and many things are missing such as
> 
> * [x]  migration,
> * [ ]  how to create widgets,
> * [x]  how to publish config to customize database model and tables,
> * [ ]  better examples,
> * [ ]  how to use the widgets as standard nova cards
> * [ ]  how to use the WidgetResource::class to direcly link to a view using collapsible-resource-mananger
> * [ ]  write docs for the value-widget and the chartjs-widget
