### ISSUE TITLE
Nova 4 compatibility

### ISSUE THREAD

**Issue by cord** [dcasia/nova-dashboard#57]
Hey @milewski,

any plans to support Nova 4?

The Nova 4 compatibility of the  dashboard manager is depending on this package, see https://github.com/Nova-BI/nova-dashboard-manager/issues/29

**Comment by muhammadsaeedparacha** [comment]
Bump

**Comment by denniselsinga** [comment]
Are there plans for Nova 4 ?

**Comment by scramatte** [comment]
Any update about nova 4 support?
