### ISSUE TITLE
Feature Request: Saving dashboard setups for general (re)use / sharing

### ISSUE THREAD

**Issue by marctich** [dcasia/nova-dashboard#7]
It'd be nice if user is able to setup a dashboard and save it so other users can see it (or re-use it as a base).

**Comment by milewski** [comment]
You already can do that, create a view and call —>editable()—>private()  this way only who created it will be able to see the widgets on that specific view , if you don't call private it will be public so everyone can see.. You can control who can edit it by passing a callback to the —>editable() returning true/false

**Comment by marctich** [comment]
Awesome, thanks!
