### ISSUE TITLE
Filters' width

### ISSUE THREAD

**Issue by philipbaginski** [dcasia/nova-dashboard#72]
In docs : 
![](https://raw.githubusercontent.com/dcasia/nova-dashboard/main/screenshots/filter-dark.png)

we can see, that filters have set up width. What is method to archive it?

**Comment by milewski** [comment]
I don't understand your question, you wanna have your filters in 2 columns? if so that`s already the default, if you have 2 filters it will by default show like the screenshot above...

but if you want 3 columns for example you could do something like this:

```php
NovaDashboard::make()
  ->addView('Main', fn (View $view) => $view
      ->addWidget(...)
      ->addFilters([...]))
  ->withMeta([ 'columns' => 3 ]),
```

**Comment by philipbaginski** [comment]
> I don't understand your question, you wanna have your filters in 2 columns? if so that`s already the default, if you have 2 filters it will by default show like the screenshot above...
> 
> but if you want 3 columns for example you could do something like this:
> 
> ```
> NovaDashboard::make()
>   ->addView('Main', fn (View $view) => $view
>       ->addWidget(...)
>       ->addFilters([...]))
>   ->withMeta([ 'columns' => 3 ]),
> ```

Thank you :-)
