### ISSUE TITLE
Full Example

### ISSUE THREAD

**Issue by alexfleites** [dcasia/nova-dashboard#73]
Hi, can you provide a full example of how to use this package in Laravel Nova. I need a dashboard where I can filter my current cards.

![Image 2024-01-10 at 7 24 06 PM](https://github.com/dcasia/nova-dashboard/assets/962479/7f4739e7-aaa9-42ee-9827-152eac4c63d4)

**Comment by milewski** [comment]
This package doesn't work directly with these nova cards, currently you could archive something similar with: https://github.com/dcasia/value-widget and https://github.com/dcasia/chartjs-widget.
