### ISSUE TITLE
Value Widget

### ISSUE THREAD

**Issue by marctich** [dcasia/nova-dashboard#8]
Love the changes you made, however I'm getting a few errors on the value widget now.

Not sure if it's me though, you git it working in combination with nova-dashboard?

````
Error in render: "TypeError: Cannot read property 'Increase' of null"

found in

---> <Widget> at resources/js/components/Widget.vue
`````

````
Missing required prop: "card"

found in

---> <Widget> at resources/js/components/Widget.vue
````

**Comment by milewski** [comment]
Hey on the dev-master I'm still working on it, if you use the tagged version `v0.0.1` it should be working

**Comment by milewski** [comment]
Fixed
